FROM eclipse-mosquitto:1.4.10
MAINTAINER Miguel Ponce de Leon <miguel@tssg.org>
ENV build_date 2017-11-23

RUN apk --no-cache add mosquitto-clients

# Changing to a working tmp directory
WORKDIR /mosquitto
